"""
GDPR / privacy compliance models.

ConsentRecord: immutable, per-purpose log of consent decisions (GDPR Art. 7(1)
requires consent to be demonstrable). user_id is nullable so anonymous
visitors can record cookie consent before registering; a stable client_id
generated by the frontend groups those anonymous decisions.

DataDeletionRequest: user-initiated right-to-erasure workflow. Rows are kept
after processing for the audit trail; the user row itself is anonymized (not
deleted) so financial/lease records retain their foreign keys.
"""
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Index
from sqlalchemy.orm import relationship

from app.models.base import Base
from app.utils.time import utc_now


class ConsentRecord(Base):
    __tablename__ = "consent_records"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    client_id = Column(String(64), nullable=True, index=True)  # anonymous visitor identifier
    # Purpose of the consent decision: cookie_analytics, cookie_marketing, tos, etc.
    consent_type = Column(String(50), nullable=False, index=True)
    granted = Column(Boolean, nullable=False, default=False)
    policy_version = Column(String(20), nullable=False, default="1.0")
    ip_address = Column(String(50), nullable=True)
    user_agent = Column(String(255), nullable=True)
    created_at = Column(DateTime, nullable=False, default=utc_now, index=True)

    user = relationship("User", foreign_keys=[user_id])


class DataDeletionRequest(Base):
    __tablename__ = "data_deletion_requests"

    id = Column(Integer, primary_key=True, index=True)
    # SET NULL (not CASCADE): the record must survive even though deletion
    # anonymizes (not removes) the user row. Nullable because a hard-deleted
    # user row nulls this out instead of destroying the audit trail.
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    # pending, completed, cancelled, declined
    status = Column(String(20), nullable=False, default="pending", index=True)
    reason = Column(Text, nullable=True)
    requested_at = Column(DateTime, nullable=False, default=utc_now)
    processed_at = Column(DateTime, nullable=True)
    processed_by = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    notes = Column(Text, nullable=True)

    user = relationship("User", foreign_keys=[user_id])

    __table_args__ = (
        Index("ix_data_deletion_requests_user_status", "user_id", "status"),
    )
