"""
PDF document generation (leases, invoices) built on fpdf2.

Generated PDFs are cached under DOCUMENTS_DIR keyed by entity id and a stamp
of the entity's updated_at, so edits produce a new file and stale artifacts
for the same entity are pruned. Documents are served only through
authenticated endpoints - never from a static mount.
"""
import logging
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

from fpdf import FPDF

from app.config.settings import ROOT_DIR, settings

logger = logging.getLogger(__name__)


def _latin(text: Optional[str]) -> str:
    """Core PDF fonts are latin-1 only; substitute anything outside that range."""
    if text is None:
        return "-"
    return text.encode("latin-1", "replace").decode("latin-1")


def _fmt_date(value: Optional[datetime]) -> str:
    return value.strftime("%d %b %Y") if value else "-"


class _DocumentPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(15, 118, 110)
        self.cell(0, 10, "PropNoxa", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(15, 118, 110)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by PropNoxa - page {self.page_no()}/{{nb}}", align="C")


def _pair_rows(pdf: FPDF, rows: list) -> None:
    """Render label/value rows as a simple two-column table."""
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(30, 41, 59)
    for label, value in rows:
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(55, 8, _latin(label))
        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 8, _latin(str(value)), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)


def _signature_block(pdf: FPDF) -> None:
    pdf.ln(14)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(85, 6, "Landlord / Agent signature: ____________________")
    pdf.cell(0, 6, "Tenant signature: ____________________", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.cell(85, 6, "Date: ____________________")
    pdf.cell(0, 6, "Date: ____________________", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        "Electronic execution: this document is not electronically signed. PropNoxa records "
        "intent via platform events; a qualified e-signature provider (e.g. DocuSign) is "
        "required for legally binding electronic signatures.",
    )


def generate_lease_pdf(lease, tenant, unit, property_obj) -> bytes:
    pdf = _DocumentPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, f"Residential Lease Agreement #{lease.id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    _pair_rows(pdf, [
        ("Property", f"{property_obj.name}, {property_obj.address or ''} {property_obj.city or ''}".strip()),
        ("Unit", f"#{unit.unit_number} ({unit.unit_type or 'unit'})" if unit else f"#{lease.unit_id}"),
        ("Tenant", getattr(tenant, "full_name", None) or "-"),
        ("Status", lease.status),
        ("Start date", _fmt_date(lease.start_date)),
        ("End date", _fmt_date(lease.end_date)),
        ("Monthly rent", f"{lease.rent_amount}"),
        ("Deposit", lease.deposit or "-"),
        ("Rent due day", f"Day {lease.payment_due_date} of each month" if lease.payment_due_date else "-"),
        ("Notes", lease.notes or "-"),
    ])

    pdf.set_font("helvetica", "", 9)
    pdf.multi_cell(
        0, 5,
        "Terms: the tenant agrees to pay rent on or before the due date each month, to keep the "
        "unit in good condition, and to observe the house rules of the property. The deposit is "
        "held against damages and unpaid rent and is settled at the end of the tenancy.",
    )
    _signature_block(pdf)
    return bytes(pdf.output())


def generate_invoice_pdf(payment, tenant, property_obj) -> bytes:
    pdf = _DocumentPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, f"Invoice #{payment.id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    _pair_rows(pdf, [
        ("Billed to", getattr(tenant, "full_name", None) or "-"),
        ("Property", property_obj.name if property_obj else f"#{payment.property_id}"),
        ("Payment type", payment.payment_type or "Rent"),
        ("Status", payment.status),
        ("Due date", _fmt_date(payment.due_date)),
        ("Payment date", _fmt_date(payment.payment_date)),
        ("Method", payment.payment_method or "-"),
        ("Reference", payment.reference or "-"),
    ])

    pdf.set_draw_color(15, 118, 110)
    pdf.set_line_width(0.4)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(120, 10, "Amount due")
    pdf.cell(0, 10, f"{payment.amount}", align="R", new_x="LMARGIN", new_y="NEXT")

    if payment.notes:
        pdf.ln(4)
        pdf.set_font("helvetica", "", 9)
        pdf.multi_cell(0, 5, _latin(f"Notes: {payment.notes}"))
    return bytes(pdf.output())


def _documents_root() -> Path:
    path = Path(settings.DOCUMENTS_DIR)
    if not path.is_absolute():
        path = ROOT_DIR / path
    path.mkdir(parents=True, exist_ok=True)
    return path


def cached_pdf(kind: str, entity_id: int, stamp: datetime, builder: Callable[[], bytes]) -> Path:
    """
    Return a cached PDF path for (kind, entity_id), regenerating when the
    entity's stamp changed. Prunes stale artifacts for the same entity.
    """
    stamp_text = stamp.strftime("%Y%m%d%H%M%S") if stamp else "nodate"
    root = _documents_root()
    target = root / f"{kind}-{entity_id}-{stamp_text}.pdf"
    if not target.exists():
        target.write_bytes(builder())
        for stale in root.glob(f"{kind}-{entity_id}-*.pdf"):
            if stale != target:
                stale.unlink(missing_ok=True)
        logger.info("Generated %s", target.name)
    return target
