"""add_ecosystem_tables

Revision ID: f82fd04ad360
Revises: 0018_sub_location
Create Date: 2026-10-01 17:27:06.665783
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f82fd04ad360'
down_revision: Union[str, Sequence[str], None] = '0018_sub_location'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('operating_areas', sa.String(length=255), nullable=True),
    sa.Column('specialties', sa.String(length=255), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_profiles_id'), 'agent_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_user_id'), 'agent_profiles', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('manager_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('operating_areas', sa.String(length=255), nullable=True),
    sa.Column('max_managed_units', sa.Integer(), nullable=True),
    sa.Column('emergency_phone', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_profiles_id'), 'manager_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_manager_profiles_user_id'), 'manager_profiles', ['user_id'], unique=True)
    op.create_table('owner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('tax_pin', sa.String(length=100), nullable=True),
    sa.Column('national_id_number', sa.String(length=100), nullable=True),
    sa.Column('payout_phone', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_profiles_id'), 'owner_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_owner_profiles_user_id'), 'owner_profiles', ['user_id'], unique=True)
    op.create_table('service_provider_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('hourly_rate', sa.String(length=50), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('service_areas', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_provider_profiles_id'), 'service_provider_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_service_provider_profiles_user_id'), 'service_provider_profiles', ['user_id'], unique=True)
    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_locations', sa.String(length=255), nullable=True),
    sa.Column('min_budget', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('preferred_bedrooms', sa.Integer(), nullable=True),
    sa.Column('preferred_property_type', sa.String(length=50), nullable=True),
    sa.Column('desired_move_in_date', sa.String(length=50), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('has_pets', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('monthly_income', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_profiles_id'), 'tenant_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_profiles_user_id'), 'tenant_profiles', ['user_id'], unique=True)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_type', sa.String(length=100), nullable=False),
    sa.Column('submitted_data_json', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_entity_id'), 'verification_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_verification_records_entity_type'), 'verification_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_verification_records_id'), 'verification_records', ['id'], unique=False)
    op.create_index(op.f('ix_verification_records_status'), 'verification_records', ['status'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('units_count', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_property_id'), 'buildings', ['property_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_context_type'), 'conversations', ['context_type'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_property_id'), 'conversations', ['property_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_conversation', sa.String(length=50), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_id'), 'conversation_participants', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('prospect_name', sa.String(length=255), nullable=True),
    sa.Column('prospect_email', sa.String(length=255), nullable=True),
    sa.Column('prospect_phone', sa.String(length=100), nullable=True),
    sa.Column('estimated_budget', sa.String(length=100), nullable=True),
    sa.Column('preferred_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('commission_amount', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prospect_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_inquiry_id'), 'leads', ['inquiry_id'], unique=False)
    op.create_index(op.f('ix_leads_property_id'), 'leads', ['property_id'], unique=False)
    op.create_index(op.f('ix_leads_prospect_id'), 'leads', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('is_system_event', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('rental_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('desired_move_in_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_income', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=100), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('credit_score_range', sa.String(length=50), nullable=True),
    sa.Column('occupants_count', sa.Integer(), nullable=True),
    sa.Column('has_pets', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=100), nullable=True),
    sa.Column('references_json', sa.Text(), nullable=True),
    sa.Column('documents_json', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_applications_applicant_id'), 'rental_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_rental_applications_id'), 'rental_applications', ['id'], unique=False)
    op.create_index(op.f('ix_rental_applications_property_id'), 'rental_applications', ['property_id'], unique=False)
    op.create_index(op.f('ix_rental_applications_status'), 'rental_applications', ['status'], unique=False)
    op.create_index(op.f('ix_rental_applications_unit_id'), 'rental_applications', ['unit_id'], unique=False)
    op.create_table('viewings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('viewing_date', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_viewing_host_schedule', 'viewings', ['host_user_id', 'viewing_date', 'start_time'], unique=False)
    op.create_index(op.f('ix_viewings_host_user_id'), 'viewings', ['host_user_id'], unique=False)
    op.create_index(op.f('ix_viewings_id'), 'viewings', ['id'], unique=False)
    op.create_index(op.f('ix_viewings_property_id'), 'viewings', ['property_id'], unique=False)
    op.create_index(op.f('ix_viewings_prospect_id'), 'viewings', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_viewings_status'), 'viewings', ['status'], unique=False)
    op.create_index(op.f('ix_viewings_unit_id'), 'viewings', ['unit_id'], unique=False)
    op.create_index(op.f('ix_viewings_viewing_date'), 'viewings', ['viewing_date'], unique=False)
    op.create_table('application_review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['rental_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_review_history_application_id'), 'application_review_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_review_history_id'), 'application_review_history', ['id'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('inspection_type', sa.String(length=50), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('condition_checklist_json', sa.Text(), nullable=True),
    sa.Column('photo_urls_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('overall_condition', sa.String(length=50), nullable=True),
    sa.Column('tenant_signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_records_id'), 'inspection_records', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_records_inspection_type'), 'inspection_records', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_inspection_records_lease_id'), 'inspection_records', ['lease_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_property_id'), 'inspection_records', ['property_id'], unique=False)
    op.create_index(op.f('ix_inspection_records_unit_id'), 'inspection_records', ['unit_id'], unique=False)
    op.create_table('maintenance_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_quotes_id'), 'maintenance_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_quotes_maintenance_id'), 'maintenance_quotes', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_quotes_provider_id'), 'maintenance_quotes', ['provider_id'], unique=False)
    op.create_index(op.f('ix_maintenance_quotes_status'), 'maintenance_quotes', ['status'], unique=False)
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completion_photos_json', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['maintenance_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_work_orders_id'), 'maintenance_work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_maintenance_id'), 'maintenance_work_orders', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_provider_id'), 'maintenance_work_orders', ['provider_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.alter_column('leases', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_recipient_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_unread'), table_name='notifications')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('properties', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('building_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('amenities', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('furnishing', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('parking_spaces', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_index(op.f('ix_properties_building_id'), 'properties', ['building_id'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_is_verified'), 'properties', ['is_verified'], unique=False)
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_property_building', 'properties', 'buildings', ['building_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'properties', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('roles_csv', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'roles_csv')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint('fk_property_building', 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_verified'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_building_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_column('properties', 'is_verified')
    op.drop_column('properties', 'parking_spaces')
    op.drop_column('properties', 'furnishing')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'building_id')
    op.drop_column('properties', 'agent_id')
    op.alter_column('payments', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_recipient_unread'), 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_created'), 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.alter_column('leases', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_provider_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_maintenance_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_id'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_quotes_status'), table_name='maintenance_quotes')
    op.drop_index(op.f('ix_maintenance_quotes_provider_id'), table_name='maintenance_quotes')
    op.drop_index(op.f('ix_maintenance_quotes_maintenance_id'), table_name='maintenance_quotes')
    op.drop_index(op.f('ix_maintenance_quotes_id'), table_name='maintenance_quotes')
    op.drop_table('maintenance_quotes')
    op.drop_index(op.f('ix_inspection_records_unit_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_property_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_lease_id'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_inspection_type'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_id'), table_name='inspection_records')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_application_review_history_id'), table_name='application_review_history')
    op.drop_index(op.f('ix_application_review_history_application_id'), table_name='application_review_history')
    op.drop_table('application_review_history')
    op.drop_index(op.f('ix_viewings_viewing_date'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_unit_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_status'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_prospect_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_property_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_host_user_id'), table_name='viewings')
    op.drop_index('ix_viewing_host_schedule', table_name='viewings')
    op.drop_table('viewings')
    op.drop_index(op.f('ix_rental_applications_unit_id'), table_name='rental_applications')
    op.drop_index(op.f('ix_rental_applications_status'), table_name='rental_applications')
    op.drop_index(op.f('ix_rental_applications_property_id'), table_name='rental_applications')
    op.drop_index(op.f('ix_rental_applications_id'), table_name='rental_applications')
    op.drop_index(op.f('ix_rental_applications_applicant_id'), table_name='rental_applications')
    op.drop_table('rental_applications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_prospect_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_property_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_inquiry_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_property_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_context_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_buildings_property_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_verification_records_status'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_entity_type'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_entity_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_tenant_profiles_user_id'), table_name='tenant_profiles')
    op.drop_index(op.f('ix_tenant_profiles_id'), table_name='tenant_profiles')
    op.drop_table('tenant_profiles')
    op.drop_index(op.f('ix_service_provider_profiles_user_id'), table_name='service_provider_profiles')
    op.drop_index(op.f('ix_service_provider_profiles_id'), table_name='service_provider_profiles')
    op.drop_table('service_provider_profiles')
    op.drop_index(op.f('ix_owner_profiles_user_id'), table_name='owner_profiles')
    op.drop_index(op.f('ix_owner_profiles_id'), table_name='owner_profiles')
    op.drop_table('owner_profiles')
    op.drop_index(op.f('ix_manager_profiles_user_id'), table_name='manager_profiles')
    op.drop_index(op.f('ix_manager_profiles_id'), table_name='manager_profiles')
    op.drop_table('manager_profiles')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_profiles_user_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
